In [6]:
#упр1
i = int(input())
def fib(n , c={0:0,1:1}):
    if n in c:
          return c[n]
    c[n]= fib(n-1)+fib(n-2)
    return c[n]
print(fib(i))

89


In [8]:
#упр2
n = int(input())
for i in range(2, n):
    if n % i == 0:
        print(i)
        n = n/i
else: n = n 

        
            

2
19
31


In [32]:
#упр3

Hello World


In [6]:
#упр4
A = list(input().split())
size = int(A[0])
symb = str(A[1])
def triangle(size, symb):
    for i in range(1, size + 1):
        print(symb * min(i, size - i + 1))
triangle(size, symb)

e
ee
eee
eeee
eeeee
eeeeee
eeeeeee
eeeeeeee
eeeeeeeee
eeeeeeeeee
eeeeeeeeee
eeeeeeeee
eeeeeeee
eeeeeee
eeeeee
eeeee
eeee
eee
ee
e


In [9]:
#упр5
import numpy as np
n = int(input())
m = int(input())
def spiral(n,m):
    A = np.zeros((n,m))
    a , i , j = 1 , 0 , 0
    while (a < m*n):
            while (j+1 < m and A[i][j+1]==0 ):
                A[i][j] = a
                a += 1
                j += 1
            while(i+1 < n and A[i+1][j]==0 ):   
                A[i][j] = a
                a += 1
                i += 1 
            while (j > 0 and A[i][j-1]==0 ):
                A[i][j] = a
                a += 1
                j -= 1
            while(i > 0 and A[i-1][j]==0 ):   
                A[i][j] = a
                a += 1
                i -= 1 
    A[i][j] = a
    return A
print(spiral(n,m))

[[ 1.  2.  3.  4.  5.]
 [14. 15. 16. 17.  6.]
 [13. 20. 19. 18.  7.]
 [12. 11. 10.  9.  8.]]


In [12]:
#упр6

import numpy as np
x = list(input().split())
y = list(input().split())
def mnk(x,y):
    x = np.array(x)
    y = np.array(y)
    a = ((x*y).mean() - x.mean()*y.mean()) / x.mean()**2
    b = y.mean() - a*x.mean()
    return a,b
print(mnk(x,y))


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None